// Code generated by "enumer -type=ClientOpcode,ServerOpcode -trimprefix=Op -output=enumer.go"; DO NOT EDIT.

package realmd

import (
	"fmt"
	"strings"
)

const _ClientOpcodeName = "ClientCharCreateClientCharListClientCharDeleteClientPlayerLoginClientLogoutForceClientLogoutRequestClientLogoutCancelClientStandStateChangeClientPingClientAuthSessionClientGetStorageClientPutStorageClientRealmSplitClientGetUnixTimeClientReadyForAccountDataTimes"
const _ClientOpcodeLowerName = "clientcharcreateclientcharlistclientchardeleteclientplayerloginclientlogoutforceclientlogoutrequestclientlogoutcancelclientstandstatechangeclientpingclientauthsessionclientgetstorageclientputstorageclientrealmsplitclientgetunixtimeclientreadyforaccountdatatimes"

var _ClientOpcodeMap = map[ClientOpcode]string{
	54:   _ClientOpcodeName[0:16],
	55:   _ClientOpcodeName[16:30],
	56:   _ClientOpcodeName[30:46],
	61:   _ClientOpcodeName[46:63],
	74:   _ClientOpcodeName[63:80],
	75:   _ClientOpcodeName[80:99],
	78:   _ClientOpcodeName[99:117],
	257:  _ClientOpcodeName[117:139],
	476:  _ClientOpcodeName[139:149],
	493:  _ClientOpcodeName[149:166],
	522:  _ClientOpcodeName[166:182],
	523:  _ClientOpcodeName[182:198],
	908:  _ClientOpcodeName[198:214],
	1270: _ClientOpcodeName[214:231],
	1279: _ClientOpcodeName[231:261],
}

func (i ClientOpcode) String() string {
	if str, ok := _ClientOpcodeMap[i]; ok {
		return str
	}
	return fmt.Sprintf("ClientOpcode(%d)", i)
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ClientOpcodeNoOp() {
	var x [1]struct{}
	_ = x[OpClientCharCreate-(54)]
	_ = x[OpClientCharList-(55)]
	_ = x[OpClientCharDelete-(56)]
	_ = x[OpClientPlayerLogin-(61)]
	_ = x[OpClientLogoutForce-(74)]
	_ = x[OpClientLogoutRequest-(75)]
	_ = x[OpClientLogoutCancel-(78)]
	_ = x[OpClientStandStateChange-(257)]
	_ = x[OpClientPing-(476)]
	_ = x[OpClientAuthSession-(493)]
	_ = x[OpClientGetStorage-(522)]
	_ = x[OpClientPutStorage-(523)]
	_ = x[OpClientRealmSplit-(908)]
	_ = x[OpClientGetUnixTime-(1270)]
	_ = x[OpClientReadyForAccountDataTimes-(1279)]
}

var _ClientOpcodeValues = []ClientOpcode{OpClientCharCreate, OpClientCharList, OpClientCharDelete, OpClientPlayerLogin, OpClientLogoutForce, OpClientLogoutRequest, OpClientLogoutCancel, OpClientStandStateChange, OpClientPing, OpClientAuthSession, OpClientGetStorage, OpClientPutStorage, OpClientRealmSplit, OpClientGetUnixTime, OpClientReadyForAccountDataTimes}

var _ClientOpcodeNameToValueMap = map[string]ClientOpcode{
	_ClientOpcodeName[0:16]:         OpClientCharCreate,
	_ClientOpcodeLowerName[0:16]:    OpClientCharCreate,
	_ClientOpcodeName[16:30]:        OpClientCharList,
	_ClientOpcodeLowerName[16:30]:   OpClientCharList,
	_ClientOpcodeName[30:46]:        OpClientCharDelete,
	_ClientOpcodeLowerName[30:46]:   OpClientCharDelete,
	_ClientOpcodeName[46:63]:        OpClientPlayerLogin,
	_ClientOpcodeLowerName[46:63]:   OpClientPlayerLogin,
	_ClientOpcodeName[63:80]:        OpClientLogoutForce,
	_ClientOpcodeLowerName[63:80]:   OpClientLogoutForce,
	_ClientOpcodeName[80:99]:        OpClientLogoutRequest,
	_ClientOpcodeLowerName[80:99]:   OpClientLogoutRequest,
	_ClientOpcodeName[99:117]:       OpClientLogoutCancel,
	_ClientOpcodeLowerName[99:117]:  OpClientLogoutCancel,
	_ClientOpcodeName[117:139]:      OpClientStandStateChange,
	_ClientOpcodeLowerName[117:139]: OpClientStandStateChange,
	_ClientOpcodeName[139:149]:      OpClientPing,
	_ClientOpcodeLowerName[139:149]: OpClientPing,
	_ClientOpcodeName[149:166]:      OpClientAuthSession,
	_ClientOpcodeLowerName[149:166]: OpClientAuthSession,
	_ClientOpcodeName[166:182]:      OpClientGetStorage,
	_ClientOpcodeLowerName[166:182]: OpClientGetStorage,
	_ClientOpcodeName[182:198]:      OpClientPutStorage,
	_ClientOpcodeLowerName[182:198]: OpClientPutStorage,
	_ClientOpcodeName[198:214]:      OpClientRealmSplit,
	_ClientOpcodeLowerName[198:214]: OpClientRealmSplit,
	_ClientOpcodeName[214:231]:      OpClientGetUnixTime,
	_ClientOpcodeLowerName[214:231]: OpClientGetUnixTime,
	_ClientOpcodeName[231:261]:      OpClientReadyForAccountDataTimes,
	_ClientOpcodeLowerName[231:261]: OpClientReadyForAccountDataTimes,
}

var _ClientOpcodeNames = []string{
	_ClientOpcodeName[0:16],
	_ClientOpcodeName[16:30],
	_ClientOpcodeName[30:46],
	_ClientOpcodeName[46:63],
	_ClientOpcodeName[63:80],
	_ClientOpcodeName[80:99],
	_ClientOpcodeName[99:117],
	_ClientOpcodeName[117:139],
	_ClientOpcodeName[139:149],
	_ClientOpcodeName[149:166],
	_ClientOpcodeName[166:182],
	_ClientOpcodeName[182:198],
	_ClientOpcodeName[198:214],
	_ClientOpcodeName[214:231],
	_ClientOpcodeName[231:261],
}

// ClientOpcodeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ClientOpcodeString(s string) (ClientOpcode, error) {
	if val, ok := _ClientOpcodeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ClientOpcodeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ClientOpcode values", s)
}

// ClientOpcodeValues returns all values of the enum
func ClientOpcodeValues() []ClientOpcode {
	return _ClientOpcodeValues
}

// ClientOpcodeStrings returns a slice of all String values of the enum
func ClientOpcodeStrings() []string {
	strs := make([]string, len(_ClientOpcodeNames))
	copy(strs, _ClientOpcodeNames)
	return strs
}

// IsAClientOpcode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ClientOpcode) IsAClientOpcode() bool {
	_, ok := _ClientOpcodeMap[i]
	return ok
}

const _ServerOpcodeName = "ServerCharCreateServerCharListServerCharDeleteServerCharLoginFailedServerSetTimeSpeedServerLogoutServerLogoutCompleteServerLogoutCancelACKServerUpdateObjectServerPlayCinematicServerTutorialFlagsServerActionButtonsServerInitialSpellsServerHearthLocationServerPongServerAuthChallengeServerAuthResponseServerAccountStorageTimesServerGetStorageServerCharLoginVerifyWorldServerStandStateServerInitialWorldStatesServerMOTDServerRealmSplitServerSystemFeaturesServerPutStorageOKServerUnixTime"
const _ServerOpcodeLowerName = "servercharcreateservercharlistserverchardeleteservercharloginfailedserversettimespeedserverlogoutserverlogoutcompleteserverlogoutcancelackserverupdateobjectserverplaycinematicservertutorialflagsserveractionbuttonsserverinitialspellsserverhearthlocationserverpongserverauthchallengeserverauthresponseserveraccountstoragetimesservergetstorageservercharloginverifyworldserverstandstateserverinitialworldstatesservermotdserverrealmsplitserversystemfeaturesserverputstorageokserverunixtime"

var _ServerOpcodeMap = map[ServerOpcode]string{
	58:   _ServerOpcodeName[0:16],
	59:   _ServerOpcodeName[16:30],
	60:   _ServerOpcodeName[30:46],
	65:   _ServerOpcodeName[46:67],
	66:   _ServerOpcodeName[67:85],
	76:   _ServerOpcodeName[85:97],
	77:   _ServerOpcodeName[97:117],
	79:   _ServerOpcodeName[117:138],
	169:  _ServerOpcodeName[138:156],
	250:  _ServerOpcodeName[156:175],
	253:  _ServerOpcodeName[175:194],
	297:  _ServerOpcodeName[194:213],
	298:  _ServerOpcodeName[213:232],
	341:  _ServerOpcodeName[232:252],
	477:  _ServerOpcodeName[252:262],
	492:  _ServerOpcodeName[262:281],
	494:  _ServerOpcodeName[281:299],
	521:  _ServerOpcodeName[299:324],
	524:  _ServerOpcodeName[324:340],
	566:  _ServerOpcodeName[340:366],
	669:  _ServerOpcodeName[366:382],
	706:  _ServerOpcodeName[382:406],
	829:  _ServerOpcodeName[406:416],
	907:  _ServerOpcodeName[416:432],
	969:  _ServerOpcodeName[432:452],
	1123: _ServerOpcodeName[452:470],
	1271: _ServerOpcodeName[470:484],
}

func (i ServerOpcode) String() string {
	if str, ok := _ServerOpcodeMap[i]; ok {
		return str
	}
	return fmt.Sprintf("ServerOpcode(%d)", i)
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ServerOpcodeNoOp() {
	var x [1]struct{}
	_ = x[OpServerCharCreate-(58)]
	_ = x[OpServerCharList-(59)]
	_ = x[OpServerCharDelete-(60)]
	_ = x[OpServerCharLoginFailed-(65)]
	_ = x[OpServerSetTimeSpeed-(66)]
	_ = x[OpServerLogout-(76)]
	_ = x[OpServerLogoutComplete-(77)]
	_ = x[OpServerLogoutCancelACK-(79)]
	_ = x[OpServerUpdateObject-(169)]
	_ = x[OpServerPlayCinematic-(250)]
	_ = x[OpServerTutorialFlags-(253)]
	_ = x[OpServerActionButtons-(297)]
	_ = x[OpServerInitialSpells-(298)]
	_ = x[OpServerHearthLocation-(341)]
	_ = x[OpServerPong-(477)]
	_ = x[OpServerAuthChallenge-(492)]
	_ = x[OpServerAuthResponse-(494)]
	_ = x[OpServerAccountStorageTimes-(521)]
	_ = x[OpServerGetStorage-(524)]
	_ = x[OpServerCharLoginVerifyWorld-(566)]
	_ = x[OpServerStandState-(669)]
	_ = x[OpServerInitialWorldStates-(706)]
	_ = x[OpServerMOTD-(829)]
	_ = x[OpServerRealmSplit-(907)]
	_ = x[OpServerSystemFeatures-(969)]
	_ = x[OpServerPutStorageOK-(1123)]
	_ = x[OpServerUnixTime-(1271)]
}

var _ServerOpcodeValues = []ServerOpcode{OpServerCharCreate, OpServerCharList, OpServerCharDelete, OpServerCharLoginFailed, OpServerSetTimeSpeed, OpServerLogout, OpServerLogoutComplete, OpServerLogoutCancelACK, OpServerUpdateObject, OpServerPlayCinematic, OpServerTutorialFlags, OpServerActionButtons, OpServerInitialSpells, OpServerHearthLocation, OpServerPong, OpServerAuthChallenge, OpServerAuthResponse, OpServerAccountStorageTimes, OpServerGetStorage, OpServerCharLoginVerifyWorld, OpServerStandState, OpServerInitialWorldStates, OpServerMOTD, OpServerRealmSplit, OpServerSystemFeatures, OpServerPutStorageOK, OpServerUnixTime}

var _ServerOpcodeNameToValueMap = map[string]ServerOpcode{
	_ServerOpcodeName[0:16]:         OpServerCharCreate,
	_ServerOpcodeLowerName[0:16]:    OpServerCharCreate,
	_ServerOpcodeName[16:30]:        OpServerCharList,
	_ServerOpcodeLowerName[16:30]:   OpServerCharList,
	_ServerOpcodeName[30:46]:        OpServerCharDelete,
	_ServerOpcodeLowerName[30:46]:   OpServerCharDelete,
	_ServerOpcodeName[46:67]:        OpServerCharLoginFailed,
	_ServerOpcodeLowerName[46:67]:   OpServerCharLoginFailed,
	_ServerOpcodeName[67:85]:        OpServerSetTimeSpeed,
	_ServerOpcodeLowerName[67:85]:   OpServerSetTimeSpeed,
	_ServerOpcodeName[85:97]:        OpServerLogout,
	_ServerOpcodeLowerName[85:97]:   OpServerLogout,
	_ServerOpcodeName[97:117]:       OpServerLogoutComplete,
	_ServerOpcodeLowerName[97:117]:  OpServerLogoutComplete,
	_ServerOpcodeName[117:138]:      OpServerLogoutCancelACK,
	_ServerOpcodeLowerName[117:138]: OpServerLogoutCancelACK,
	_ServerOpcodeName[138:156]:      OpServerUpdateObject,
	_ServerOpcodeLowerName[138:156]: OpServerUpdateObject,
	_ServerOpcodeName[156:175]:      OpServerPlayCinematic,
	_ServerOpcodeLowerName[156:175]: OpServerPlayCinematic,
	_ServerOpcodeName[175:194]:      OpServerTutorialFlags,
	_ServerOpcodeLowerName[175:194]: OpServerTutorialFlags,
	_ServerOpcodeName[194:213]:      OpServerActionButtons,
	_ServerOpcodeLowerName[194:213]: OpServerActionButtons,
	_ServerOpcodeName[213:232]:      OpServerInitialSpells,
	_ServerOpcodeLowerName[213:232]: OpServerInitialSpells,
	_ServerOpcodeName[232:252]:      OpServerHearthLocation,
	_ServerOpcodeLowerName[232:252]: OpServerHearthLocation,
	_ServerOpcodeName[252:262]:      OpServerPong,
	_ServerOpcodeLowerName[252:262]: OpServerPong,
	_ServerOpcodeName[262:281]:      OpServerAuthChallenge,
	_ServerOpcodeLowerName[262:281]: OpServerAuthChallenge,
	_ServerOpcodeName[281:299]:      OpServerAuthResponse,
	_ServerOpcodeLowerName[281:299]: OpServerAuthResponse,
	_ServerOpcodeName[299:324]:      OpServerAccountStorageTimes,
	_ServerOpcodeLowerName[299:324]: OpServerAccountStorageTimes,
	_ServerOpcodeName[324:340]:      OpServerGetStorage,
	_ServerOpcodeLowerName[324:340]: OpServerGetStorage,
	_ServerOpcodeName[340:366]:      OpServerCharLoginVerifyWorld,
	_ServerOpcodeLowerName[340:366]: OpServerCharLoginVerifyWorld,
	_ServerOpcodeName[366:382]:      OpServerStandState,
	_ServerOpcodeLowerName[366:382]: OpServerStandState,
	_ServerOpcodeName[382:406]:      OpServerInitialWorldStates,
	_ServerOpcodeLowerName[382:406]: OpServerInitialWorldStates,
	_ServerOpcodeName[406:416]:      OpServerMOTD,
	_ServerOpcodeLowerName[406:416]: OpServerMOTD,
	_ServerOpcodeName[416:432]:      OpServerRealmSplit,
	_ServerOpcodeLowerName[416:432]: OpServerRealmSplit,
	_ServerOpcodeName[432:452]:      OpServerSystemFeatures,
	_ServerOpcodeLowerName[432:452]: OpServerSystemFeatures,
	_ServerOpcodeName[452:470]:      OpServerPutStorageOK,
	_ServerOpcodeLowerName[452:470]: OpServerPutStorageOK,
	_ServerOpcodeName[470:484]:      OpServerUnixTime,
	_ServerOpcodeLowerName[470:484]: OpServerUnixTime,
}

var _ServerOpcodeNames = []string{
	_ServerOpcodeName[0:16],
	_ServerOpcodeName[16:30],
	_ServerOpcodeName[30:46],
	_ServerOpcodeName[46:67],
	_ServerOpcodeName[67:85],
	_ServerOpcodeName[85:97],
	_ServerOpcodeName[97:117],
	_ServerOpcodeName[117:138],
	_ServerOpcodeName[138:156],
	_ServerOpcodeName[156:175],
	_ServerOpcodeName[175:194],
	_ServerOpcodeName[194:213],
	_ServerOpcodeName[213:232],
	_ServerOpcodeName[232:252],
	_ServerOpcodeName[252:262],
	_ServerOpcodeName[262:281],
	_ServerOpcodeName[281:299],
	_ServerOpcodeName[299:324],
	_ServerOpcodeName[324:340],
	_ServerOpcodeName[340:366],
	_ServerOpcodeName[366:382],
	_ServerOpcodeName[382:406],
	_ServerOpcodeName[406:416],
	_ServerOpcodeName[416:432],
	_ServerOpcodeName[432:452],
	_ServerOpcodeName[452:470],
	_ServerOpcodeName[470:484],
}

// ServerOpcodeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ServerOpcodeString(s string) (ServerOpcode, error) {
	if val, ok := _ServerOpcodeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ServerOpcodeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ServerOpcode values", s)
}

// ServerOpcodeValues returns all values of the enum
func ServerOpcodeValues() []ServerOpcode {
	return _ServerOpcodeValues
}

// ServerOpcodeStrings returns a slice of all String values of the enum
func ServerOpcodeStrings() []string {
	strs := make([]string, len(_ServerOpcodeNames))
	copy(strs, _ServerOpcodeNames)
	return strs
}

// IsAServerOpcode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ServerOpcode) IsAServerOpcode() bool {
	_, ok := _ServerOpcodeMap[i]
	return ok
}
